=== dhruvkb/reschume/schema/resume.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://dhruvkb.github.io/reschume/schema/resume.json",

  "type": "object",
  "properties": {
    "bio": { "$ref": "bio.json" },
    "education": { "$ref": "education.json" },
    "creations": { "$ref": "creations.json" },
    "work": { "$ref": "work.json" }
  }
}

=== dhruvkb/reschume/sample_data/dhruvkb.json
{
  "$schema": "https://dhruvkb.github.io/reschume/schema/resume.json",
  "bio": {
    "name": "Dhruv Bhanushali",
    "image": "https://www.gravatar.com/avatar/0eab64adad056cff2492e7c407a9aa21?s=256",
    "label": "Software developer and open-source maintainer",
    "summary": "Software engineer @ WordPress/Openverse • IIT-R '19",
    "contact": {
      "emails": ["hi@dhruvkb.dev"]
    },
    "social": [
      {
        "id": "github",
        "name": "GitHub",
        "username": "dhruvkb",
        "url": "https://github.com/dhruvkb"
      },
      {
        "id": "linkedin",
        "name": "LinkedIn",
        "username": "dhruvkb",
        "url": "https://www.linkedin.com/in/dhruvkb"
      },
      {
        "id": "instagram",
        "name": "Instagram",
        "username": "dhruvkb_",
        "url": "https://www.instagram.com/dhruvkb_/"
      }
    ],
    "address": {
      "city": "Navi Mumbai",
      "state": "Maharashtra",
      "countryCode": "IN"
    },
    "skills": [
      { "name": "Java", "subskills": ["Swing", "JavaFX", "Android"] },
      { "name": "Kotlin", "subskills": ["Android"] },
      { "name": "Ruby", "subskills": ["Rails"] },
      { "name": "Swift", "subskills": ["SwiftUI"] },
      "Golang",
      "Rust",
      "C++",
      "PHP",
      "Bash"
    ]
  },
  "education": [
    {
      "id": "iitr",
      "name": "Indian Institute of Technology, Roorkee",
      "shortName": "IIT-R",
      "url": "https://iitr.ac.in",
      "address": {
        "city": "Roorkee",
        "state": "Haridwar",
        "countryCode": "IN"
      },
      "certifications": [
        {
          "id": "b_tech",
          "name": "B. Tech.",
          "field": "Engineering Physics",
          "score": "7.286",
          "maxScore": "10.000",
          "period": {
            "start": [2015],
            "end": [2019]
          }
        }
      ]
    }
  ],
  "work": [
    {
      "id": "automattic",
      "name": "Automattic",
      "url": "https://automattic.com",
      "roles": [
        {
          "id": "code_wrangler",
          "name": "Code wrangler",
          "period": {
            "start": [2021, 4]
          },
          "type": "full-timer",
          "epicIds": ["openverse"],
          "isFeatured": true,
          "highlights": [
            "Developed the <a href=\"https://wordpress.org/openverse\">Openverse</a> media search engine.",
            "Worked on features with the WordPress FOSS community.",
            "Onboarded & mentored new open source contributors."
          ]
        }
      ]
    },
    {
      "id": "wordpress",
      "name": "WordPress",
      "shortName": "WP",
      "url": "https://wordpress.org/openverse/",
      "roles": [
        {
          "id": "project_maintainer",
          "name": "Project maintainer",
          "period": {
            "start": [2021, 4]
          },
          "type": "foss-contributor",
          "epicIds": ["openverse"]
        }
      ]
    },
    {
      "id": "center_of_ci",
      "name": "Center of CI",
      "shortName": "CCI",
      "url": "https://centerofci.org",
      "roles": [
        {
          "id": "software_engineer",
          "name": "Software engineer",
          "period": {
            "start": [2021, 6]
          },
          "type": "part-timer"
        }
      ]
    },
    {
      "id": "browserstack",
      "name": "BrowserStack",
      "url": "https://browserstack.com",
      "roles": [
        {
          "id": "software_engineer",
          "name": "Software engineer",
          "period": {
            "start": [2020, 2],
            "end": [2021, 3]
          },
          "type": "full-timer",
          "isFeatured": true,
          "highlights": [
            "Identified & fixed issues tantamount to a GDPR breach.",
            "Built audit logs to prevent, detect & alert for breaches.",
            "Integrated all email providers with the Central Email System.",
            "Created system to track & visualise email engagement.",
            "Set up systems to improve email deliverability & reputation."
          ]
        }
      ]
    },
    {
      "id": "creative_commons",
      "name": "Creative Commons",
      "shortName": "CC",
      "url": "https://creativecommons.org",
      "roles": [
        {
          "id": "project_maintainer",
          "name": "Project maintainer",
          "period": {
            "start": [2019, 9]
          },
          "type": "foss-contributor",
          "epicIds": ["vocabulary"]
        },
        {
          "id": "foss_community_coordinator",
          "name": "FOSS community coordinator",
          "period": {
            "start": [2020, 7],
            "end": [2020, 12]
          },
          "type": "contractor",
          "isFeatured": true,
          "highlights": [
            "Identified, organised & triaged issues & reviewed PRs.",
            "Onboarded & mentored new open source contributors.",
            "Maintained the <a href=\"https://github.com/creativecommons/creativecommons.github.io-source/\">open-source site</a> and <a href=\"https://github.com/creativecommons/ccos-scripts/\">automation workflows</a>.",
            "Increased reach & engagement of the <a href=\"https://twitter.com/cc_opensource\">official Twitter</a> handle."
          ]
        },
        {
          "id": "foss_internship_mentor",
          "name": "Internship mentor",
          "period": {
            "start": [2019, 12],
            "end": [2020, 12]
          },
          "type": "foss-contributor",
          "isFeatured": true,
          "highlights": [
            "Onboarded & guided applicants through the processes.",
            "Reviewed, scored & ranked proposals from candidates.",
            "Mentored <b>Google Season of Docs</b> in 2020.",
            "Mentored <b>Outreachy</b> in winter 2019-20 & summer 2020."
          ]
        },
        {
          "id": "gsoc_engineer",
          "name": "GSoC engineer",
          "period": {
            "start": [2019, 5],
            "end": [2019, 8]
          },
          "type": "intern",
          "isFeatured": true,
          "highlights": [
            "Conceived, designed & developed Vocabulary from scratch.",
            "Initiated & supported Vocabulary integration with CC sites."
          ]
        }
      ]
    },
    {
      "id": "fampay",
      "name": "FamPay",
      "url": "https://fampay.in",
      "roles": [
        {
          "id": "software_engineer",
          "name": "Software engineer",
          "period": {
            "start": [2019, 11],
            "end": [2019, 12]
          },
          "type": "part-timer",
          "isFeatured": true,
          "highlights": [
            "Developed the end-to-end payment flow for the application.",
            "Integrated with Razorpay and Cashfree payment gateways."
          ]
        }
      ]
    },
    {
      "id": "hackerearth",
      "name": "HackerEarth",
      "url": "https://hackerearth.com",
      "roles": [
        {
          "id": "infrastructure_engineer",
          "name": "Infrastructure engineer",
          "period": {
            "start": [2018, 5],
            "end": [2018, 7]
          },
          "type": "intern",
          "isFeatured": true,
          "highlights": [
            "Wrote the IaC for the entire production architecture.",
            "Created tooling to deploy the IaC in an alternate AWS AZ.",
            "Developed scripts to launch and terminate EC2 instances.",
            "Isolated staging env from production in a separate VPC.",
            "Enabled one‑click provisioning of staging environments."
          ]
        },
        {
          "id": "software_engineer",
          "name": "Software engineer",
          "period": {
            "start": [2017, 5],
            "end": [2017, 7]
          },
          "type": "intern",
          "isFeatured": true,
          "highlights": [
            "Wrote a code‑evaluation engine to evaluate Java projects.",
            "Created tooling to automatically build and execute projects.",
            "Wrapped Ant in an async message‑based Python evaluator.",
            "Developed the scaffolding architecture using RabbitMQ.",
            "Added provider‑agnostic database connectivity using JDBC.",
            "Installed security policies such as memory and I/O limits."
          ]
        }
      ]
    },
    {
      "id": "img",
      "name": "IMG, IIT Roorkee",
      "shortName": "IMG IIT-R",
      "summary": "Information Management Group (IMG) is the student body that developed, manages and upgrades both the CMS powering the IIT-R website and Omniport, the official intranet portal.",
      "url": "https://img.channeli.in",
      "roles": [
        {
          "id": "chief_coordinator_tech",
          "name": "Chief coordinator (tech)",
          "period": {
            "start": [2016, 1],
            "end": [2019, 4]
          },
          "type": "part-timer",
          "epicIds": ["omniport"],
          "highlights": [
            "Pivoted IMG as a group from app to platform development.",
            "Upgraded the legacy portal, tech stack & apps to <a href=\"https://omniport.readthedocs.io/\">Omniport</a>.",
            "Containerised, decoupled & stabilised dev processes.",
            "Halved timelines by revamping the development paradigm.",
            "Mentored a team of over 50 developers and designers.",
            "Fostered <a href=\"https://github.com/IMGIITRoorkee/\">OSS culture</a> by open-sourcing 40+ repos.",
            "Led IMG to 10 and 13 GSoC selections in 2018 and 2019.",
            "Reinvigorated IMG's popular image on various <a href=\"https://facebook.com/IMGIITRoorkee\">social media</a>."
          ]
        }
      ]
    }
  ],
  "creations": [
    {
      "id": "reschume",
      "name": "Réschumé",
      "projects": [
        {
          "id": "schema",
          "name": "Résumé schema",
          "url": "https://dhruvkb.github.io/reschume",
